server:
    port: 8082
    servlet:
        context-path: /api/v1
spring:
    application:
        name: excel-upload-service
    servlet:
        multipart:
            enabled: true
            max-file-size: 4MB
            max-request-size: 5MB
